version: "3"
services:
  fastify-app:
    container_name: "fastify"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    command: "npm run dev"
